### ISSUE TITLE
concatenate all histograms and create a new one which will be used to represent the image.

### ISSUE THREAD

**Issue by tuji-sjp** [kelvins/lbph#2]
Please tell me how to do this work？How to concatenate in detail？Thank you！

**Comment by kelvins** [comment]
@tuji-sjp I could not understand your question. This is a step of the algorithm, we don't need to do it manually. To use the algorithm, please follow this [example](https://github.com/kelvins/lbph#usage-example).

To know more about the algorithm steps, please read [this article](https://towardsdatascience.com/face-recognition-how-lbph-works-90ec258c3d6b).

Just to answer your question, the concatenation is quite simple:

Histogram 1: [1, 2, 3, 4]
Histogram 2: [3, 6, 7, 8]
Histogram 3: [4, 2, 7, 8]

Concatenated histogram: [1, 2, 3, 4, 3, 6, 7, 8, 4, 2, 7, 8]

**Comment by tuji-sjp** [comment]
@kelvins Thank you very mucn, I get it.

**Comment by tuji-sjp** [comment]
@kelvins Thank you very much! This algorithm is almost clear to me. But I haven't learned the R. Could you tell me the version of python?

**Comment by kelvins** [comment]
@tuji-sjp this algorithm is implemented in Go, not Python. If you want to implement this algorithm in an easier language I would suggest you implement using Matlab.

**Comment by tuji-sjp** [comment]
@kelvins Please excuse my ignorance. Why should I use Matlab instead of python?

**Comment by kelvins** [comment]
@tuji-sjp It all depends on your purpose, but in general, Matlab provide some easier functions for example to load images, work with matrices, apply statistical functions, and so on. If you are implementing it for academic purposes I would suggest to use Matlab or R. Otherwise, if you are implementing it for commercial use I would suggest to use Python, G, C++, amongst other languages.

**Comment by tuji-sjp** [comment]
@kelvins Ok, thank you！

**Comment by kelvins** [comment]
You're welcome!
